spring.application.name=GatePass
spring.data.mongodb.uri=mongodb+srv://prisonudpatel_db_user:5p9rraVgjIakPynX@cluster0.xj98btd.mongodb.net/?appName=Cluster0
#spring.data.mongodb.port=27017
spring.data.mongodb.database=visitorDB
spring.data.mongodb.auto-index-creation=true
#6xeKmfQgxyGYnSFp
#5p9rraVgjIakPynX
#prisonudpatel_db_user